name: "Python: Lint, format & type check"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Analysis
    steps:
      - uses: actions/checkout@v5
      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.14.3
      - name: Check format with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
          version: 0.14.3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Type check with Mypy
        run: uv run mypy .
      - name: Type check Jupyter notebooks with Mypy (via nbqa)
        run: uv run nbqa mypy .
